/**
 * Deterministic calendar of scheduled events relevant to Bitcoin investors.
 *
 * Why this file exists: previously countdown_events were generated by Claude
 * from training data (cutoff Jan 2026), which produced hallucinated or stale
 * dates (wrong FOMC days, options expiry on a Saturday, etc.). Shipping wrong
 * dates on a paid briefing is a trust-killer.
 *
 * This file is the single source of truth. The AI brain prompt is given this
 * list verbatim and told to pick ONLY from it. After Claude returns, a
 * validator drops any event whose (name, date) pair is not in this file.
 *
 * ─────────────────────────────────────────────────────────────────────────
 *  MAINTENANCE: this file ships dates manually curated from official sources.
 *  Verify these at least once per year:
 *    - FOMC schedule:    https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm
 *    - CPI releases:     https://www.bls.gov/schedule/news_release/cpi.htm
 *    - Jobs reports:     https://www.bls.gov/schedule/news_release/empsit.htm
 *    - PCE releases:     https://www.bea.gov/news/schedule
 *  Options expiry is computed mechanically (Deribit: last Friday of month,
 *  08:00 UTC). Halving is block-based (~block 1,050,000) and is emitted
 *  with a ±14 day caveat in its description.
 * ─────────────────────────────────────────────────────────────────────────
 */

export type KnownEventKind =
  | "fomc"
  | "cpi"
  | "jobs"
  | "pce"
  | "halving"
  | "options_expiry";

export interface KnownEvent {
  kind: KnownEventKind;
  name: string;        // Canonical display name shown on the site
  date: string;        // ISO date "YYYY-MM-DD"
  description: string; // One-line description for the UI card
}

// ─── FOMC meeting decisions (source: federalreserve.gov) ─────────────────
// The FOMC releases its statement on the SECOND day of each two-day meeting.
// We emit the release date, not day 1.
//
// 2026: https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm
// Dates below are the scheduled statement-release days for 2026.
const FOMC_DATES: string[] = [
  "2026-01-28",
  "2026-03-18",
  "2026-04-29",
  "2026-06-17",
  "2026-07-29",
  "2026-09-16",
  "2026-10-28",
  "2026-12-09",
  // 2027 — scheduled dates published by Fed in June 2026.
  // TODO: refresh after June 2026 release.
  "2027-01-27",
  "2027-03-17",
  "2027-04-28",
  "2027-06-16",
  "2027-07-28",
  "2027-09-22",
  "2027-11-03",
  "2027-12-15",
];

// ─── CPI release dates (source: bls.gov/schedule/news_release/cpi.htm) ───
// BLS release for the PRIOR month's inflation data. Released 08:30 ET.
// Format: [release_date, data_month]
const CPI_RELEASES: Array<{ date: string; dataMonth: string }> = [
  { date: "2026-01-14", dataMonth: "December 2025" },
  { date: "2026-02-11", dataMonth: "January 2026" },
  { date: "2026-03-11", dataMonth: "February 2026" },
  { date: "2026-04-10", dataMonth: "March 2026" },
  { date: "2026-05-13", dataMonth: "April 2026" },
  { date: "2026-06-11", dataMonth: "May 2026" },
  { date: "2026-07-15", dataMonth: "June 2026" },
  { date: "2026-08-12", dataMonth: "July 2026" },
  { date: "2026-09-10", dataMonth: "August 2026" },
  { date: "2026-10-15", dataMonth: "September 2026" },
  { date: "2026-11-13", dataMonth: "October 2026" },
  { date: "2026-12-10", dataMonth: "November 2026" },
  // TODO: add 2027 dates once BLS publishes them (typically Nov of prior year).
];

// ─── Jobs report (NFP) release dates ─────────────────────────────────────
// BLS Employment Situation, typically first Friday of each month, 08:30 ET.
// Source: bls.gov/schedule/news_release/empsit.htm
const JOBS_RELEASES: Array<{ date: string; dataMonth: string }> = [
  { date: "2026-01-09", dataMonth: "December 2025" },
  { date: "2026-02-06", dataMonth: "January 2026" },
  { date: "2026-03-06", dataMonth: "February 2026" },
  { date: "2026-04-03", dataMonth: "March 2026" },
  { date: "2026-05-01", dataMonth: "April 2026" },
  { date: "2026-06-05", dataMonth: "May 2026" },
  { date: "2026-07-02", dataMonth: "June 2026" },
  { date: "2026-08-07", dataMonth: "July 2026" },
  { date: "2026-09-04", dataMonth: "August 2026" },
  { date: "2026-10-02", dataMonth: "September 2026" },
  { date: "2026-11-06", dataMonth: "October 2026" },
  { date: "2026-12-04", dataMonth: "November 2026" },
];

// ─── PCE release dates (source: bea.gov/news/schedule) ───────────────────
// Personal Income and Outlays, typically last Friday of each month.
const PCE_RELEASES: Array<{ date: string; dataMonth: string }> = [
  { date: "2026-01-30", dataMonth: "December 2025" },
  { date: "2026-02-27", dataMonth: "January 2026" },
  { date: "2026-03-27", dataMonth: "February 2026" },
  { date: "2026-04-30", dataMonth: "March 2026" },
  { date: "2026-05-29", dataMonth: "April 2026" },
  { date: "2026-06-26", dataMonth: "May 2026" },
  { date: "2026-07-31", dataMonth: "June 2026" },
  { date: "2026-08-28", dataMonth: "July 2026" },
  { date: "2026-09-25", dataMonth: "August 2026" },
  { date: "2026-10-30", dataMonth: "September 2026" },
  { date: "2026-11-25", dataMonth: "October 2026" },
  { date: "2026-12-23", dataMonth: "November 2026" },
];

// ─── Bitcoin halving (next one) ──────────────────────────────────────────
// Block-based, not calendar-based. Next halving at block 1,050,000 (reward
// 3.125 → 1.5625). Estimate derived from average block time. Shown with a
// ±14 day caveat in the description since block time can drift.
const NEXT_HALVING_DATE = "2028-04-20";

// ─── Deribit BTC monthly options expiry ──────────────────────────────────
// Computed mechanically: last Friday of each month, 08:00 UTC.

function lastFridayOfMonth(year: number, month0: number): Date {
  // month0 is 0-indexed (Jan = 0). Get last day of month.
  const lastDay = new Date(Date.UTC(year, month0 + 1, 0));
  // day-of-week: 0 = Sunday, 5 = Friday
  const dow = lastDay.getUTCDay();
  const offset = (dow - 5 + 7) % 7;
  const day = lastDay.getUTCDate() - offset;
  return new Date(Date.UTC(year, month0, day));
}

function formatIsoDate(d: Date): string {
  return d.toISOString().split("T")[0];
}

function buildOptionsExpiries(fromDate: Date, monthsAhead: number = 6): KnownEvent[] {
  const out: KnownEvent[] = [];
  const startYear = fromDate.getUTCFullYear();
  const startMonth = fromDate.getUTCMonth();
  for (let i = 0; i < monthsAhead; i++) {
    const y = startYear + Math.floor((startMonth + i) / 12);
    const m = (startMonth + i) % 12;
    const expiry = lastFridayOfMonth(y, m);
    if (expiry < fromDate) continue;
    const isoMonth = expiry.toLocaleString("en-US", { month: "long", timeZone: "UTC" });
    out.push({
      kind: "options_expiry",
      name: `${isoMonth} Bitcoin Options Expiry`,
      date: formatIsoDate(expiry),
      description: "Monthly Deribit BTC options expiry, last Friday 08:00 UTC. Watch for open-interest skew near max pain.",
    });
  }
  return out;
}

// ─── Public API ──────────────────────────────────────────────────────────

/**
 * Return all known events in a window starting at `fromDate` (inclusive),
 * up to `windowDays` days ahead. Used to build the FACTS BLOCK for the AI
 * brain prompt.
 */
export function getUpcomingKnownEvents(
  fromDateIso: string,
  windowDays: number = 90
): KnownEvent[] {
  const from = new Date(fromDateIso + "T00:00:00Z");
  const until = new Date(from);
  until.setUTCDate(until.getUTCDate() + windowDays);

  const events: KnownEvent[] = [];

  for (const d of FOMC_DATES) {
    const dt = new Date(d + "T00:00:00Z");
    if (dt >= from && dt <= until) {
      events.push({
        kind: "fomc",
        name: "FOMC Meeting",
        date: d,
        description: "Federal Reserve interest rate decision, 2:00 PM ET statement and 2:30 PM ET press conference.",
      });
    }
  }

  for (const r of CPI_RELEASES) {
    const dt = new Date(r.date + "T00:00:00Z");
    if (dt >= from && dt <= until) {
      events.push({
        kind: "cpi",
        name: "CPI Report",
        date: r.date,
        description: `${r.dataMonth} consumer price inflation data, released 08:30 ET by the BLS.`,
      });
    }
  }

  for (const r of JOBS_RELEASES) {
    const dt = new Date(r.date + "T00:00:00Z");
    if (dt >= from && dt <= until) {
      events.push({
        kind: "jobs",
        name: "Jobs Report",
        date: r.date,
        description: `${r.dataMonth} Employment Situation (Non-Farm Payrolls), released 08:30 ET by the BLS.`,
      });
    }
  }

  for (const r of PCE_RELEASES) {
    const dt = new Date(r.date + "T00:00:00Z");
    if (dt >= from && dt <= until) {
      events.push({
        kind: "pce",
        name: "PCE Inflation",
        date: r.date,
        description: `${r.dataMonth} PCE price index, the Fed's preferred inflation gauge, released 08:30 ET by the BEA.`,
      });
    }
  }

  // Halving is far out; include only if within window.
  const halving = new Date(NEXT_HALVING_DATE + "T00:00:00Z");
  if (halving >= from && halving <= until) {
    events.push({
      kind: "halving",
      name: "Next Bitcoin Halving",
      date: NEXT_HALVING_DATE,
      description: "Block reward drops from 3.125 to 1.5625 BTC at block 1,050,000. Date is a block-time estimate, ±14 days.",
    });
  }

  // Monthly options expiries (mechanical).
  events.push(...buildOptionsExpiries(from, Math.ceil(windowDays / 30) + 1).filter((e) => {
    const dt = new Date(e.date + "T00:00:00Z");
    return dt >= from && dt <= until;
  }));

  // Sort by date ascending.
  events.sort((a, b) => (a.date < b.date ? -1 : a.date > b.date ? 1 : 0));

  return events;
}

/**
 * Compute days between two ISO dates (UTC midnight). Positive if `target` is
 * after `from`, negative otherwise, 0 for same day.
 */
export function daysBetween(fromIso: string, targetIso: string): number {
  const from = new Date(fromIso + "T00:00:00Z").getTime();
  const target = new Date(targetIso + "T00:00:00Z").getTime();
  return Math.round((target - from) / (1000 * 60 * 60 * 24));
}

/**
 * Validate and normalize a countdown_event emitted by Claude. Returns null if
 * the (name, date) pair is not present in the known calendar. Recomputes
 * days_away deterministically from the briefing date.
 */
export function validateCountdownEvent(
  event: { name: string; date: string; days_away: number | null; description: string },
  briefingDateIso: string,
  windowDays: number = 365 * 3
): KnownEvent & { days_away: number } | null {
  const known = getUpcomingKnownEvents(briefingDateIso, windowDays);
  // Match on (name AND date) — either alone is insufficient (e.g. two FOMC
  // meetings in the window share a name; two events on the same date would
  // share a date).
  const match = known.find(
    (k) => k.name.toLowerCase() === event.name.toLowerCase() && k.date === event.date
  );
  if (!match) return null;

  return {
    ...match,
    days_away: daysBetween(briefingDateIso, match.date),
  };
}

/**
 * Filter a list of Claude-emitted countdown_events down to only those matching
 * the known calendar, with server-computed days_away. Any event not in the
 * calendar is dropped (and logged by the caller).
 */
export function validateCountdownEvents(
  events: Array<{ name: string; date: string; days_away: number | null; description: string }>,
  briefingDateIso: string
): {
  kept: Array<{ name: string; date: string; days_away: number; description: string }>;
  dropped: Array<{ name: string; date: string; reason: string }>;
} {
  const kept: Array<{ name: string; date: string; days_away: number; description: string }> = [];
  const dropped: Array<{ name: string; date: string; reason: string }> = [];

  for (const ev of events) {
    const validated = validateCountdownEvent(ev, briefingDateIso);
    if (!validated) {
      dropped.push({
        name: ev.name,
        date: ev.date,
        reason: "not in known calendar (name+date mismatch)",
      });
      continue;
    }
    kept.push({
      name: validated.name,
      date: validated.date,
      days_away: validated.days_away,
      description: validated.description,
    });
  }

  return { kept, dropped };
}

/**
 * Build the FACTS BLOCK string injected into the AI brain user prompt. The
 * prompt instructs Claude to pick its countdown_events ONLY from this list.
 */
export function buildCountdownFactsBlock(
  briefingDateIso: string,
  windowDays: number = 90
): string {
  const events = getUpcomingKnownEvents(briefingDateIso, windowDays);
  if (events.length === 0) {
    return "No known scheduled events in the next " + windowDays + " days.";
  }
  const lines = events.map((e) => {
    const days = daysBetween(briefingDateIso, e.date);
    return `- ${e.date} (${days}d) | ${e.name} | ${e.description}`;
  });
  return lines.join("\n");
}
